<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Resources\DDrawCompat\0.6.0\ddraw.dll" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.2.6" />
      <PackageReference Include="DynamicData" Version="9.2.1" />
      <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.6.0" />
      <PackageReference Include="PatternFinder" Version="1.0.2" />
      <PackageReference Include="ReactiveUI" Version="20.1.63" />
      <PackageReference Include="sims-iff" Version="0.2.2" />
      <PackageReference Include="Sims.Far" Version="4.2.2" />
        <PackageReference Include="System.Text.Json" Version="8.0.5" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Resources\DDrawCompat\0.3.2\ddraw.dll" />
      <EmbeddedResource Include="Resources\DDrawCompat\0.6.0\ddraw.dll" />
      <None Remove="Resources\dd_domcal.iff" />
      <EmbeddedResource Include="Resources\dd_domcal.iff" />
      <None Remove="Resources\DgVoodoo2\2_86\D3D8.dll" />
      <EmbeddedResource Include="Resources\DgVoodoo2\2_86\D3D8.dll" />
      <None Remove="Resources\DgVoodoo2\2_86\D3DImm.dll" />
      <EmbeddedResource Include="Resources\DgVoodoo2\2_86\D3DImm.dll" />
      <None Remove="Resources\DgVoodoo2\2_86\DDraw.dll" />
      <EmbeddedResource Include="Resources\DgVoodoo2\2_86\DDraw.dll" />
      <None Remove="Resources\DgVoodoo2\2_86\dgVoodoo.conf" />
      <EmbeddedResource Include="Resources\DgVoodoo2\2_86\dgVoodoo.conf" />
      <None Remove="Resources\DgVoodoo2\2_86\dgVoodooCpl.exe" />
      <EmbeddedResource Include="Resources\DgVoodoo2\2_86\dgVoodooCpl.exe" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Properties\Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Resources.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Properties\Resources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

</Project>
